export enum IngestEventType {
  TEST_EVENT = 'TEST_EVENT',
  INEWS_STORY_CREATED = 'INEWS_STORY_CREATED',
  INEWS_STORY_CHANGED = 'INEWS_STORY_CHANGED',
  INEWS_STORY_MOVED = 'INEWS_STORY_MOVED',
  INEWS_STORY_DELETED = 'INEWS_STORY_DELETED',
}
